spring:

  application:
    name: encontre-me
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cep-address}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  cloud:
    openfeign:
      client:
        config:
          cep-client:
            url: ${CEP_SERVICE_URL:http://localhost:8089/}
            connectTimeout: 1000
            readTimeout: 2000
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
    time-zone: America/Sao_Paulo
server:
  port: ${SERVER_PORT:8080}

app:
  security:
    api-header: X-API-KEY
    api-key: ${API_KEY:minha-chave-lucas-lopes-cunha}
  external-services:
    cep:
      url: ${CEP_SERVICE_URL:http://localhost:8089/}
      uri-search: /api/v1/consulta/cep/{cep}
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true

resilience4j:
  ratelimiter:
    instances:
      cepConsultas:
        limitForPeriod: 3
        limitRefreshPeriod: 10s
        timeoutDuration: 0s
      logsConsultas:
        limitForPeriod: 3
        limitRefreshPeriod: 10s
        timeoutDuration: 0s

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.results: TRACE